services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: kayvan999/taskaza:latest
    container_name: taskaza-api

    # <port on localhost>:<port on container>
    ports: 
      - 8000:8000

    # creating a bind mount to keep our container and dev env in sync
    # with read only command for added security
    volumes:
      - ./backend:/usr/src/app:ro
      - ./backend/data:/usr/src/app/data
    
    # override the command to start the server with --reload
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8000
    
    env_file: ./backend/.env

    networks:
      - taskaza-nw

  db:
    image: postgres:17
    container_name: taskaza-db
    restart: always
    environment:
      POSTGRES_USER: taskaza_user
      POSTGRES_PASSWORD: taskaza_password
      POSTGRES_DB: taskaza_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - taskaza-nw

networks:
  taskaza-nw:
    driver: bridge

volumes:
  postgres_data: