services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: kayvan999/taskaza:latest
    container_name: taskaza-api

    # <port on localhost>:<port on container>
    ports: 
      - 8000:8000

    # creating a bind mount to keep our container and dev env in sync
    # with read only command for added security
    volumes:
      - ./:/usr/src/app:ro
      - ./data:/usr/src/app/data
    
    # override the command to start the server with --reload
    command: fastapi run app/main.py
    
    env_file: .env

networks:
  taskaza-network:
    driver: bridge